language: node_js

cache:
  directories:
    - ~/.npm
    - ~/.meteor
    - "node_modules"

node_js:
  - '8'

install:
  - npm install
  - curl https://install.meteor.com/ | sh
  - export PATH=$HOME/.meteor:$PATH
  - npx meteor-ci login ${METEOR_TOKEN} --key ${METEOR_KEY}
  - meteor whoami

stages:
  - test
  - release

script:
  - npm test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run semantic-release; fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
